server:
  port: 8000



spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 16
        min-idle: 8


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.tang.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.wx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"


custom:
  swaggerTitle: "在线办公系统"
  jwt:
    secrect: asdx#2s@dpx
    timeout: 1800
